# Intro and data creation

In [1]:
import dask.array as da
import dask.dataframe as dd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.tsa.api as smt

from arch import arch_model

In [2]:
%%javascript
IPython.OutputArea.auto_scroll_threshold = 9999;

<IPython.core.display.Javascript object>

In [3]:
OUTPUT_PATH = "./simulated_data/"

In [4]:
def GARCH_sim(theta, n=1000, n_iter = 1000):
    (mu,omega,alpha,beta) = theta
    nu=np.random.normal(size=(n + n_iter,))
    sigma=np.zeros((n + n_iter,))
    eps=np.zeros((n + n_iter,))
    
    for i in range(1,n+n_iter):
        sigma[i]=np.sqrt(omega+alpha*eps[i-1]**2+beta*sigma[i-1]**2)
        eps[i]=sigma[i]*nu[i]
        
    return eps[n_iter:], sigma[n_iter:]

In [5]:
returns_df=pd.read_excel('DATA_MARKETS.xlsx', 'DAILY',usecols="B:AI")
for col in returns_df.columns:
    returns_df[col]=1000*returns_df[col]
returns=np.array(returns_df)
print("Done")

Done


In [6]:
returns_df.head()

EQ_UK      EQ_SZ      EQ_CA     EQ_JN      EQ_AS      EQ_EU   EQ_SCEU  \
0  -9.801320  -4.169441  -3.791472  2.977168  13.074797  -5.571522 -0.225441   
1  13.767230  18.797430  16.008449 -0.815770  -5.119100  13.233616  5.750042   
2   5.220638  -1.269995  -7.359811 -3.708973   8.721848   8.557060  4.203800   
3   2.136577   3.643378   5.012538  4.827877  -8.656507   4.589546  0.613976   
4  16.875769   5.794007   5.401743  7.737938   5.516345   7.556675  5.299269   

       EQ_US   EQ_SCUS      EQ_GR  ...    GOV_SZ    GOV_JN    GOV_CA  \
0   0.096613 -8.857993  -4.908900  ... -4.686769  1.901668 -7.509960   
1  17.019366  7.266947  18.403567  ... -1.550899  5.591229  2.770936   
2  -2.452911 -1.429784  15.901940  ... -0.161656 -1.535597 -5.756831   
3  18.646517  9.018593   9.707932  ... -6.966412 -6.856733 -1.223358   
4  -5.834126 -3.866476  12.326930  ... -4.148291 -2.806796 -1.492422   

     GOV_US   CORP_EU   CORP_US     HY_EU     HY_US    CONV_US      D_EM  
0 -6.798712 -4.044220 -5.180136 -1.493298 -4.414943   0.304094  2.985870  
1  3.546833 -0.937864  2.610108  0.205971  1.447437   9.777936  5.347771  
2 -6.518510  1.206957 -3.907483  1.754873 -1.565325   3.793803 -0.702085  
3 -0.491404 -1.246716 -0.137288  0.250257  0.220775  10.555790  6.025640  
4  0.145416  0.082530 -0.302883  0.419969  1.218183  -1.574365  4.243624  

[5 rows x 34 columns]

In [7]:
garch_param_means=[]
garch_param_chol=[]
for col in returns_df.columns:
    garch = arch_model(returns_df[col]).fit(disp='off')
    garch_param_means.append(np.array(garch.params))
    garch_param_chol.append(np.linalg.cholesky(garch.param_cov))
garch_param_means, garch_param_chol

C:\ProgramData\Anaconda3\lib\site-packages\arch\univariate\base.py:709: ConvergenceWarning: The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  ConvergenceWarning,


([array([0.41710866, 1.77952052, 0.10735364, 0.88005783]),
  array([0.50538994, 2.78958192, 0.1164304 , 0.8620654 ]),
  array([0.47405369, 0.82987277, 0.07583916, 0.91677374]),
  array([0.53436259, 4.56104754, 0.10233185, 0.87478239]),
  array([0.62806078, 0.94017615, 0.07954585, 0.91177422]),
  array([0.74570702, 2.17156281, 0.09397777, 0.89501166]),
  array([0.92693744, 1.84441496, 0.12738568, 0.86120927]),
  array([0.58635354, 1.67932743, 0.09023901, 0.89596195]),
  array([0.70522347, 3.78506464, 0.07998686, 0.89932329]),
  array([0.83209791, 2.38924298, 0.08787944, 0.90134717]),
  array([0.72953643, 2.43825112, 0.09621223, 0.89382933]),
  array([0.44342745, 1.59503692, 0.09362977, 0.90357443]),
  array([0.81823918, 2.36682482, 0.09455528, 0.89764098]),
  array([0.90834686, 3.20556137, 0.10372649, 0.88384723]),
  array([0.70507942, 5.58998934, 0.05821624, 0.92275292]),
  array([0.99670905, 5.33543169, 0.08080402, 0.90487119]),
  array([0.54889104, 0.69463647, 0.06281003, 0.93535855]

In [ ]:
N_years_length=365
N_years_sim=30
N_sim=500
N_assets=len(returns_df.columns)

for i_year in range(N_sim):
    output_df=pd.DataFrame(columns=returns_df.columns)
    for i_asset,col in enumerate(returns_df.columns):
        sim_params=np.maximum(garch_param_means[i_asset]+np.dot(np.random.normal(size=(4)),garch_param_chol[i_asset].T),np.zeros_like(4))
        val, vol = GARCH_sim(sim_params,N_years_sim*N_years_length,1000)
        output_df[col]=val/1000
    output_df.to_csv(path_or_buf=OUTPUT_PATH+"simulation_"+str(i_year)+".csv",header=True,index=False)

# Dask kicks in

## 1) basic operations

In [8]:
import dask
from dask.distributed import Client
import dask.dataframe as dd

client = Client(n_workers=3, threads_per_worker=2, memory_limit='1GB')
client

<Client: 'tcp://127.0.0.1:52853' processes=3 threads=6, memory=3.00 GB>

In [9]:
dfs = dd.read_csv(OUTPUT_PATH+'simulation_*.csv')

In [10]:
dfs.npartitions

100

In [11]:
asset_means,asset_corr = dfs.mean(axis=0), dfs.corr()
asset_means,asset_corr

(Dask Series Structure:
 npartitions=1
 CONV_US    float64
 HY_US          ...
 dtype: float64
 Dask Name: dataframe-mean, 303 tasks, Dask DataFrame Structure:
                  EQ_UK    EQ_SZ    EQ_CA    EQ_JN    EQ_AS    EQ_EU  EQ_SCEU    EQ_US  EQ_SCUS    EQ_GR    EQ_FR    EQ_IT    EQ_SP    EM_IN    EM_BR    EM_RU    EM_KO    EM_TW    EM_CN   GOV_UK   GOV_SP   GOV_FR   GOV_GR   GOV_IT   GOV_SZ   GOV_JN   GOV_CA   GOV_US  CORP_EU  CORP_US    HY_EU    HY_US  CONV_US     D_EM
 npartitions=1                                                                                                                                                                                                                                                                                                                  
 EQ_UK          float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  fl

In [12]:
asset_means,asset_corr = dask.compute(asset_means,asset_corr)

In [13]:
asset_means

EQ_UK      9.379249e-09
EQ_SZ     -1.301480e-05
EQ_CA     -4.168823e-06
EQ_JN      1.075309e-05
EQ_AS     -6.427503e-06
EQ_EU     -2.204249e-05
EQ_SCEU    2.239920e-05
EQ_US     -5.391089e-06
EQ_SCUS    7.695105e-06
EQ_GR     -1.453334e-06
EQ_FR     -1.887423e-05
EQ_IT     -3.402993e-04
EQ_SP     -7.839031e-06
EM_IN     -1.396936e-04
EM_BR     -2.840010e-06
EM_RU      3.936591e-03
EM_KO     -3.491617e-02
EM_TW      4.769662e-05
EM_CN     -2.286743e-05
GOV_UK     3.793526e-06
GOV_SP    -9.788156e-06
GOV_FR    -6.462501e-07
GOV_GR     1.072908e-06
GOV_IT     1.804302e+07
GOV_SZ    -2.304960e-06
GOV_JN     2.103658e-02
GOV_CA     1.838521e-06
GOV_US    -4.422951e-06
CORP_EU    2.142186e-06
CORP_US    4.470381e-06
HY_EU      4.717881e+32
HY_US     -9.770125e+42
CONV_US    7.171465e-06
D_EM       2.471132e-03
dtype: float64

In [14]:
asset_corr

EQ_UK     EQ_SZ     EQ_CA     EQ_JN     EQ_AS     EQ_EU  \
EQ_UK    1.000000e+00  0.000213 -0.000579 -0.000989 -0.001704  0.001380   
EQ_SZ    2.133989e-04  1.000000  0.000840 -0.001035 -0.000177  0.000399   
EQ_CA   -5.792878e-04  0.000840  1.000000  0.000446 -0.000935  0.000244   
EQ_JN   -9.889690e-04 -0.001035  0.000446  1.000000  0.000421 -0.001905   
EQ_AS   -1.704230e-03 -0.000177 -0.000935  0.000421  1.000000  0.001592   
EQ_EU    1.380351e-03  0.000399  0.000244 -0.001905  0.001592  1.000000   
EQ_SCEU  4.145675e-04 -0.000740 -0.000080  0.000562 -0.000044  0.000620   
EQ_US   -6.055293e-04 -0.001124 -0.000087 -0.000485  0.000932  0.000853   
EQ_SCUS  4.556449e-05  0.000968  0.001418  0.001018 -0.000683  0.000962   
EQ_GR    6.022869e-04  0.000760  0.000934  0.000843 -0.000466  0.001199   
EQ_FR   -5.178758e-04  0.001480  0.001312  0.000567  0.000067 -0.000704   
EQ_IT    5.111048e-05  0.001287  0.000374 -0.000510 -0.000188 -0.000058   
EQ_SP    1.567137e-04 -0.000333  0.000862  0.000273 -0.000004 -0.001443   
EM_IN   -1.422743e-03 -0.000082  0.000136  0.000937  0.001733  0.001013   
EM_BR    7.224884e-04 -0.000250  0.000024 -0.000683 -0.000323  0.000669   
EM_RU   -5.902937e-04 -0.000397 -0.000447  0.001329  0.001573  0.001468   
EM_KO   -9.739903e-04  0.001030  0.001654  0.000291  0.000071  0.000680   
EM_TW    7.900384e-04  0.000988 -0.000342  0.000172  0.000263 -0.001213   
EM_CN    1.962036e-04  0.000754 -0.000871 -0.001951 -0.000885  0.001039   
GOV_UK  -9.627655e-05  0.000565 -0.001963  0.000034  0.000905  0.000276   
GOV_SP   5.810992e-04 -0.000140  0.000311  0.000514  0.000689 -0.000873   
GOV_FR   5.056901e-04  0.000257 -0.001353 -0.000294  0.000226  0.000029   
GOV_GR   7.414273e-04  0.000201 -0.000982 -0.001196  0.000377 -0.000837   
GOV_IT  -1.001013e-03 -0.000763  0.000510 -0.000533  0.000294 -0.000802   
GOV_SZ   5.879260e-04  0.000918  0.000668 -0.000368  0.000075  0.000006   
GOV_JN  -8.126651e-04 -0.000969  0.001045  0.001816  0.000996 -0.000520   
GOV_CA   2.111832e-07  0.001327 -0.000963 -0.001461  0.001018  0.000810   
GOV_US  -7.507996e-04  0.001494 -0.000113 -0.000554 -0.002702  0.000279   
CORP_EU -2.445545e-03 -0.002012 -0.000290  0.000419 -0.000404  0.000434   
CORP_US  1.633911e-03  0.000113  0.000328  0.000396  0.000570  0.001886   
HY_EU    7.208442e-04 -0.000796  0.003975  0.002311 -0.000375 -0.000451   
HY_US   -1.648424e-04 -0.000280  0.000559 -0.001058 -0.000704  0.001329   
CONV_US -9.248902e-04  0.000247  0.001006 -0.001085  0.000784  0.000498   
D_EM     4.664013e-04  0.001096  0.000116  0.000510  0.001284 -0.000026   

          EQ_SCEU     EQ_US       EQ_SCUS     EQ_GR  ...    GOV_SZ  \
EQ_UK    0.000415 -0.000606  4.556449e-05  0.000602  ...  0.000588   
EQ_SZ   -0.000740 -0.001124  9.675269e-04  0.000760  ...  0.000918   
EQ_CA   -0.000080 -0.000087  1.417541e-03  0.000934  ...  0.000668   
EQ_JN    0.000562 -0.000485  1.018473e-03  0.000843  ... -0.000368   
EQ_AS   -0.000044  0.000932 -6.825709e-04 -0.000466  ...  0.000075   
EQ_EU    0.000620  0.000853  9.624932e-04  0.001199  ...  0.000006   
EQ_SCEU  1.000000  0.000113  2.612797e-04 -0.000424  ... -0.000511   
EQ_US    0.000113  1.000000  1.253086e-04 -0.001896  ... -0.000058   
EQ_SCUS  0.000261  0.000125  1.000000e+00 -0.001405  ... -0.000796   
EQ_GR   -0.000424 -0.001896 -1.404655e-03  1.000000  ...  0.000055   
EQ_FR    0.001325 -0.000892 -8.332792e-04  0.001395  ...  0.001146   
EQ_IT    0.000207  0.000031 -3.249931e-04 -0.001428  ...  0.000276   
EQ_SP   -0.000046 -0.000757 -1.019706e-03 -0.000609  ... -0.000711   
EM_IN    0.001330  0.000352  1.437683e-03 -0.001211  ...  0.000358   
EM_BR   -0.000574 -0.001174 -5.285494e-07  0.001807  ...  0.000289   
EM_RU   -0.000299  0.000916 -1.180641e-03 -0.000398  ... -0.001839   
EM_KO    0.000274 -0.000225  4.068370e-04 -0.000454  ...  0.001623   
EM_TW    0.000379 -0.001218  4.328463e-04 -0.001169  ...  0.000292   
EM_CN    0.001037 -0.000672 -1.991936e-04  0.000140  ...  0.

## 2) distributed learning with sklearn
### a) dumb linear model

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn import ensemble
import joblib

In [16]:
client.close()

In [17]:
client2 = Client(n_workers=8, threads_per_worker=1, memory_limit='1GB')
client2

<Client: 'tcp://127.0.0.1:52909' processes=8 threads=8, memory=8.00 GB>

In [18]:
target_col = dfs.columns[0]
data_cols = dfs.columns[1:]

In [19]:
ridge_reg = linear_model.Ridge(alpha=.5)
ridge_reg

Ridge(alpha=0.5)

In [20]:
with joblib.parallel_backend('dask'):
    ridge_reg.fit(dfs[data_cols], dfs[target_col])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:148: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number2.528473e-101
  overwrite_a=True).T


In [21]:
ridge_reg.intercept_, ridge_reg.coef_

(2.877295146045534e-08,
 array([ 2.20332561e-04, -6.32130247e-04, -8.40364029e-04, -1.71265997e-03,
         1.14846544e-03,  2.16304873e-04, -6.41251286e-04,  3.89668034e-05,
         4.46895823e-04, -4.08035389e-04,  1.05396036e-06,  9.30835403e-05,
        -2.93911834e-05,  5.26256894e-04, -1.48577049e-06, -3.57559949e-07,
         3.68724216e-04,  5.79368201e-05, -3.41903392e-04,  2.22234063e-04,
         2.04584562e-03,  2.90343589e-03, -3.51690166e-16,  2.93229914e-03,
        -8.05167673e-07, -1.12456286e-05, -2.11223675e-03, -1.64380472e-02,
         4.65759157e-03,  1.74236186e-41, -6.34626816e-54, -1.79526037e-03,
         2.22252553e-06]))

In [22]:
with joblib.parallel_backend('dask'):
    print("r2 =", ridge_reg.score(dfs[data_cols], dfs[target_col]))

r2 = 2.5726597027708742e-05


### b) bayesian ridge

In [ ]:
bridge_reg = linear_model.BayesianRidge()
bridge_reg

In [ ]:
with joblib.parallel_backend('dask'):
    bridge_reg.fit(dfs[data_cols], dfs[target_col])
bridge_reg.intercept_, bridge_reg.coef_

In [ ]:
with joblib.parallel_backend('dask'):
    print("r2 =", bridge_reg.score(dfs[data_cols], dfs[target_col]))

## 3) distributed learning with dask_ml

In [23]:
import dask_ml.datasets
import dask_ml.cluster
import dask_ml.linear_model
import dask_ml.xgboost

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\dask\array\random.py:27: FutureWarning: dask.array.random.doc_wraps is deprecated and will be removed in a future version
  FutureWarning,
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
C:

### a) linear regression 2.0

In [ ]:
lr = dask_ml.linear_model.LinearRegression()
lr.fit(dfs[data_cols].to_dask_array(lengths=True), dfs[target_col].to_dask_array(lengths=True))

In [ ]:
lr.intercept_ , lr.coef_

In [ ]:
lr.score(dfs[data_cols], dfs[target_col])

### b) XGBoost

In [25]:
model = dask_ml.xgboost.XGBRegressor()

In [ ]:
model.fit(dfs[data_cols].to_dask_array(lengths=True), dfs[target_col].to_dask_array(lengths=True))